#!/usr/bin/env bash

# ###############################################################
# PATH
# ###############################################################

# Set path -> here.
declare CCTL="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# ###############################################################
# COMMANDS
# ###############################################################

# Infrastructure commands:
# ... binaries
alias cctl-infra-bin-compile='source $CCTL/cmds/infra/bin/compile.sh'
alias cctl-infra-bin-compile-client='source $CCTL/cmds/infra/bin/compile_client.sh'
alias cctl-infra-bin-compile-contracts='source $CCTL/cmds/infra/bin/compile_contracts.sh'
alias cctl-infra-bin-compile-node='source $CCTL/cmds/infra/bin/compile_node.sh'
alias cctl-infra-bin-compile-node-launcher='source $CCTL/cmds/infra/bin/compile_node_launcher.sh'
alias cctl-infra-bin-compile-sidecar='source $CCTL/cmds/infra/bin/compile_sidecar.sh'
# ... network
alias cctl-infra-net-setup='source $CCTL/cmds/infra/net/setup.sh'
alias cctl-infra-net-start='source $CCTL/cmds/infra/net/start.sh'
alias cctl-infra-net-status='source $CCTL/cmds/infra/net/status.sh'
alias cctl-infra-net-stop='source $CCTL/cmds/infra/net/stop.sh'
alias cctl-infra-net-teardown='source $CCTL/cmds/infra/net/teardown.sh'
alias cctl-infra-net-view-paths='source $CCTL/cmds/infra/net/view_paths.sh'
# ... node control
alias cctl-infra-node-clean='source $CCTL/cmds/infra/node/clean.sh'
alias cctl-infra-node-stop='source $CCTL/cmds/infra/node/stop.sh'
alias cctl-infra-node-restart='source $CCTL/cmds/infra/node/restart.sh'
# ... node views
alias cctl-infra-node-view-config='source $CCTL/cmds/infra/node/view_config.sh'
alias cctl-infra-node-view-error-log='source $CCTL/cmds/infra/node/view_log_stderr.sh'
alias cctl-infra-node-view-log='source $CCTL/cmds/infra/node/view_log_stdout.sh'
alias cctl-infra-node-view-metrics='source $CCTL/cmds/infra/node/view_metrics.sh'
alias cctl-infra-node-view-peers='source $CCTL/cmds/infra/node/view_peers.sh'
alias cctl-infra-node-view-peer-count='source $CCTL/cmds/infra/node/view_peer_count.sh'
alias cctl-infra-node-view-paths='source $CCTL/cmds/infra/node/view_paths.sh'
alias cctl-infra-node-view-ports='source $CCTL/cmds/infra/node/view_ports.sh'
alias cctl-infra-node-view-reactor-state='source $CCTL/cmds/infra/node/view_reactor_state.sh'
alias cctl-infra-node-view-status='source $CCTL/cmds/infra/node/view_status.sh'
alias cctl-infra-node-view-storage='source $CCTL/cmds/infra/node/view_storage.sh'
# ... sidecar views
alias cctl-infra-sidecar-view-config='source $CCTL/cmds/infra/sidecar/view_config.sh'
alias cctl-infra-sidecar-view-error-log='source $CCTL/cmds/infra/sidecar/view_log_stderr.sh'
alias cctl-infra-sidecar-view-log='source $CCTL/cmds/infra/sidecar/view_log_stdout.sh'
alias cctl-infra-sidecar-view-ports='source $CCTL/cmds/infra/sidecar/view_ports.sh'
alias cctl-infra-sidecar-view-rpc-endpoint='source $CCTL/cmds/infra/sidecar/view_rpc_endpoint.sh'
alias cctl-infra-sidecar-view-rpc-schema='source $CCTL/cmds/infra/sidecar/view_rpc_schema.sh'
alias cctl-infra-sidecar-write-rpc-schema='source $CCTL/cmds/infra/sidecar/write_rpc_schema.sh'
# Chain commands:
# ... awaiting
alias cctl-chain-await-n-blocks='source $CCTL/cmds/chain/await/n_blocks.sh'
alias cctl-chain-await-n-eras='source $CCTL/cmds/chain/await/n_eras.sh'
alias cctl-chain-await-until-block-n='source $CCTL/cmds/chain/await/until_block_n.sh'
alias cctl-chain-await-until-era-n='source $CCTL/cmds/chain/await/until_era_n.sh'
# ... views
alias cctl-chain-view-account='source $CCTL/cmds/chain/query/view_account.sh'
alias cctl-chain-view-account-address='source $CCTL/cmds/chain/query/view_account_address.sh'
alias cctl-chain-view-account-balance='source $CCTL/cmds/chain/query/view_account_balance.sh'
alias cctl-chain-view-account-balances='source $CCTL/cmds/chain/query/view_account_balances.sh'
alias cctl-chain-view-account-of-faucet='source $CCTL/cmds/chain/query/view_account_of_faucet.sh'
alias cctl-chain-view-account-of-user='source $CCTL/cmds/chain/query/view_account_of_user.sh'
alias cctl-chain-view-account-of-validator='source $CCTL/cmds/chain/query/view_account_of_validator.sh'
alias cctl-chain-view-auction-info='source $CCTL/cmds/chain/query/view_auction_info.sh'
alias cctl-chain-view-block='source $CCTL/cmds/chain/query/view_block.sh'
alias cctl-chain-view-block-transfers='source $CCTL/cmds/chain/query/view_block_transfers.sh'
alias cctl-chain-view-deploy='source $CCTL/cmds/chain/query/view_deploy.sh'
alias cctl-chain-view-era='source $CCTL/cmds/chain/query/view_era.sh'
alias cctl-chain-view-era-summary='source $CCTL/cmds/chain/query/view_era_summary.sh'
alias cctl-chain-view-genesis-accounts='source $CCTL/cmds/chain/query/view_genesis_accounts.sh'
alias cctl-chain-view-genesis-chainspec='source $CCTL/cmds/chain/query/view_genesis_chainspec.sh'
alias cctl-chain-view-height='source $CCTL/cmds/chain/query/view_height.sh'
alias cctl-chain-view-last-finalized-block='source $CCTL/cmds/chain/query/view_last_finalized_block.sh'
alias cctl-chain-view-state-root-hash='source $CCTL/cmds/chain/query/view_state_root_hash.sh'
alias cctl-chain-view-tip-info='source $CCTL/cmds/chain/query/view_tip_info.sh'
alias cctl-chain-view-validator-changes='source $CCTL/cmds/chain/query/view_validator_changes.sh'

# Transaction commands:
# ... system auction
alias cctl-tx-auction-activate-bid='source $CCTL/cmds/tx/auction/activate_bid.sh'
alias cctl-tx-auction-delegate='source $CCTL/cmds/tx/auction/delegate.sh'
alias cctl-tx-auction-add-bid='source $CCTL/cmds/tx/auction/add_bid.sh'
alias cctl-tx-auction-undelegate='source $CCTL/cmds/tx/auction/undelegate.sh'
alias cctl-tx-auction-withdraw-bid='source $CCTL/cmds/tx/auction/withdraw_bid.sh'
# ... system mint
alias cctl-tx-mint-dispatch-transfer='source $CCTL/cmds/tx/mint/dispatch_transfer.sh'
alias cctl-tx-mint-dispatch-transfer-batch='source $CCTL/cmds/tx/mint/dispatch_transfer_batch.sh'
alias cctl-tx-mint-write-transfer-batch='source $CCTL/cmds/tx/mint/write_transfer_batch.sh'
