version: '3.8'
services:
  cctl:
    build:
      context: .
      args:
        NODE_GITBRANCH: release-1.5.6
        CLIENT_GITBRANCH: release-2.0.0
    container_name: cspr-cctl
    image: cspr-cctl/release-1.5.6
    ports:
      - 25101:25101
      - 11101:11101
      - 14101:14101
      - 18101:18101
